In [2]:
import numpy as np

In [7]:
aa = np.full(5, 65500, np.uint16)
bb = np.full(5, 65500, np.uint16)
cc = aa * bb

cc

array([1296, 1296, 1296, 1296, 1296], dtype=uint16)

In [9]:
cc = np.empty(5, np.uint32)
np.multiply(aa, bb, out=cc)
cc

array([1296, 1296, 1296, 1296, 1296], dtype=uint32)

In [10]:
aa.astype(np.uint32, copy=False) * bb

array([4290250000, 4290250000, 4290250000, 4290250000, 4290250000],
      dtype=uint32)

In [8]:
[ np.iinfo(f"u{2**i}") for i in range(4) ]


[iinfo(min=0, max=255, dtype=uint8),
 iinfo(min=0, max=65535, dtype=uint16),
 iinfo(min=0, max=4294967295, dtype=uint32),
 iinfo(min=0, max=18446744073709551615, dtype=uint64)]